const SET_POSTS = 'SET_POSTS';
const LOAD_POSTS = 'LOAD_POSTS';
const ADD_POSTS = 'ADD_POSTS';
const LOAD_POST = 'LOAD_POST';
const SET_SELECTED_POST = 'SET_SELECTED_POST';
const SET_SEARCH = 'SET_SEARCH';

export {
    SET_POSTS,
    LOAD_POSTS,
    ADD_POSTS,
    LOAD_POST,
    SET_SELECTED_POST,
    SET_SEARCH,
}