const SIGN_UP = 'SIGN_UP';
const ACTIVATION_REGISTRATION = 'ACTIVATION_REGISTRATION';
const SIGN_IN= 'SIGN_IN'
const GET_USER_INFO = 'GET_USER_INFO'
const SET_USER_INFO = 'SET_USER_INFO'

export{
    SIGN_UP,
    ACTIVATION_REGISTRATION,
    SIGN_IN,
    GET_USER_INFO,
    SET_USER_INFO,
}